# Generated by Django 5.0.6 on 2024-05-29 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=20)),
                ('doc_image', models.TextField(max_length=200)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.department')),
            ],
        ),
    ]
